# Form implementation generated from reading ui file '.\UI\form_account.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
import Account as acc
import Form_Parking


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 188)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(160, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 0, 31, 31))
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setPixmap(QtGui.QPixmap(".\\UI\\../image/1077114.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.account = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.account.setGeometry(QtCore.QRect(130, 50, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.account.setFont(font)
        self.account.setObjectName("account")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(130, 80, 191, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setObjectName("password")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.btn_login.clicked.connect(self.CheckLogin)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Account"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
    
    def CheckLogin(self):
        Account = self.account.text()
        Password = self.password.text()
        if acc.Check_Account(Account,Password):
            print("Login Success")
            self.open_form_parking()
            MainWindow.hide()
        else:
            print("Login failed")

    def open_form_parking(self):
        self.form_parking_window = QMainWindow()  # Tạo một cửa sổ chính mới
        self.ui_form_parking = Form_Parking.Ui_MainWindow()  # Tạo thể hiện của Ui_MainWindow
        self.ui_form_parking.setupUi(self.form_parking_window)  # Cài đặt giao diện cho cửa sổ
        self.form_parking_window.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
