create table employee(
    ID_emp VARCHAR(10) PRIMARY KEY,
    name_emp NCHAR(50),
    phone VARCHAR(11) CHECK (phone like '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    salary float,
    work_hour float,
    stt number(1)
);

create TABLE accounts(
    ID_emp VARCHAR(10),
    ID_acc VARCHAR(11) PRIMARY KEY,
    pass_acc VARCHAR(20),
    stt NUMBER(1)
);

alter table accounts add (constraint ID_emp_acc_fk foreign key (ID_emp) references employee(ID_emp));

Create table timekeeping(
    ID_emp VARCHAR(10),
    ID_check INTEGER GENERATED BY DEFAULT AS IDENTITY,
    time_check TIMESTAMP,
    Total FLOAT
);
alter table timekeeping add (constraint ID_emp_check_fk foreign key (ID_emp) references employee(ID_emp));

create table moto(
    Id_moto varchar(20),
    time_in TIMESTAMP,
    ID_emp VARCHAR(10),
    time_out TIMESTAMP,
    fee FLOAT,
    stt NUMBER(1) NOT NULL
);

alter table moto add (constraint ID_emp_moto_fk foreign key (ID_emp) references employee(ID_emp))


INSERT INTO employee (ID_emp, name_emp, phone, salary, work_hour, stt) 
VALUES ('NV01', N'Lê Tu?n Ngh?a', '0909383703', 5000, 0, 1);


INSERT INTO accounts (ID_emp, id_acc, pass_acc, stt) 
VALUES ('NV01', 'Anhpr0cd1', '0909383703', 1);

Insert into moto(id_moto, time_in,id_emp,time_out,fee,stt)
values('64-B2 22697',TO_DATE('08/29/2024', 'MM/DD/YYYY'), 'NV01',NULL, NULL,0)

SELECT * FROM moto 